# Generated by Django 5.0.6 on 2024-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('father_Name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
